# Generated by Django 5.0.14 on 2026-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_municipality_user_neighborhood_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='doc_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
