# Generated by Django 5.0.14 on 2026-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20260723_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurity',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
