# Generated by Django 5.0.14 on 2026-09-02 15:06

import security.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersecurity_two_factor_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='doc_number_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='doc_number',
            field=security.encryption.EncryptedCharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usersecurity',
            name='two_factor_secret',
            field=security.encryption.EncryptedCharField(blank=True, max_length=2048),
        ),
    ]
