# Generated by Django 5.0.14 on 2026-09-02 16:37

import django.db.models.deletion
import django.utils.timezone
import security.encryption
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_identitydocument_doc_number_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='doc_number',
            field=security.encryption.EncryptedCharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usersecurity',
            name='two_factor_secret',
            field=security.encryption.EncryptedCharField(blank=True, max_length=2048),
        ),
        migrations.CreateModel(
            name='DataPrivacyConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(default='v1.2-sandbox-bna', max_length=50)),
                ('privacy_policy_version', models.CharField(default='v1.2-apd-lei2211', max_length=50)),
                ('terms_content_hash', models.CharField(help_text='Hash SHA-256 do conteúdo integral dos termos aceites', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentimento de Privacidade (APD)',
                'verbose_name_plural': 'Consentimentos de Privacidade (APD)',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('country_code', models.CharField(default='AO', max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_anomalous', models.BooleanField(db_index=True, default=False)),
                ('anomaly_reasons', models.JSONField(blank=True, default=list)),
                ('login_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Login',
                'verbose_name_plural': 'Históricos de Login',
                'ordering': ['-login_at'],
            },
        ),
    ]
