# Generated by Django 5.0.14 on 2026-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_latitude_offer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Ex: ["Multicaixa Express", "Wise", "PayPal"]'),
        ),
    ]
