# Generated by Django 5.0.14 on 2026-09-02 15:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('related_offer_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('related_transaction_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('rule_code', models.CharField(choices=[('STRUCTURING_SMURFING', 'Fracionamento / Smurfing de Valores'), ('HIGH_VELOCITY', 'Pico de Velocidade / Frequência Anômala'), ('LARGE_VALUE_ALERT', 'Operação de Grande Volume (LVTR)'), ('RATE_OUTLIER', 'Desvio Cambial Excessivo da Taxa BNA'), ('TIER_LIMIT_EXCEEDED', 'Tentativa de Exceder Limite de KYC'), ('HIGH_RISK_USER', 'Utilizador com Múltiplas Denúncias/Alto Risco'), ('SUSPICIOUS_PATTERN', 'Padrão Suspeito Indefinido')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='MEDIUM', max_length=15)),
                ('risk_score', models.PositiveIntegerField(default=50)),
                ('amount_aoa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pendente de Revisão'), ('UNDER_INVESTIGATION', 'Em Investigação'), ('ESCALATED_TO_UIF', 'Reportado à UIF (Unidade de Informação Financeira)'), ('DISMISSED_FALSE_POSITIVE', 'Arquivado / Falso Positivo'), ('RESOLVED_BLOCKED', 'Resolvido com Bloqueio de Conta')], db_index=True, default='PENDING_REVIEW', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_to_uif_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_aml_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Atividade Suspeita (SAR/DOS)',
                'verbose_name_plural': 'Relatórios de Atividades Suspeitas (SAR/DOS)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_tier', models.CharField(choices=[('TIER_0_UNVERIFIED', 'Tier 0 - Não Verificado (Sem Acesso Monetário)'), ('TIER_1_BASIC', 'Tier 1 - Básico (Em Análise / Limite Baixo)'), ('TIER_2_VERIFIED', 'Tier 2 - Verificado Completo (BI + Selfie)'), ('TIER_3_BUSINESS', 'Tier 3 - Empresarial / PME (Alta Capacidade)')], db_index=True, default='TIER_0_UNVERIFIED', max_length=30)),
                ('risk_score', models.PositiveIntegerField(default=10, help_text='Score de 0 a 100')),
                ('is_pep', models.BooleanField(default=False, help_text='Pessoa Exposta Politicamente')),
                ('is_sanctioned', models.BooleanField(default=False, help_text='Listas de Sanções Internacionais/Nacionais')),
                ('is_high_risk', models.BooleanField(default=False)),
                ('total_completed_volume_aoa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Risco do Utilizador',
                'verbose_name_plural': 'Perfis de Risco dos Utilizadores',
            },
        ),
    ]
