# Generated by Django 5.0.14 on 2026-09-02 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_suspiciousactivityreport_userriskprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('sha256_checksum', models.CharField(help_text='Hash SHA-256 para integridade à prova de adulteração', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Em Execução'), ('SUCCESS', 'Concluído com Sucesso'), ('VERIFIED', 'Verificado & Testado'), ('FAILED', 'Falha na Execução')], db_index=True, default='PENDING', max_length=20)),
                ('encrypted_with', models.CharField(default='AES-256-Fernet', max_length=50)),
                ('storage_location', models.CharField(default='local_encrypted_storage', max_length=255)),
                ('duration_seconds', models.FloatField(default=0.0, help_text='Tempo de execução do backup')),
                ('is_dr_tested', models.BooleanField(default=False, help_text='Se passou no teste de recuperação de desastres')),
                ('dr_test_at', models.DateTimeField(blank=True, null=True)),
                ('dr_test_rto_seconds', models.FloatField(blank=True, help_text='Tempo real medido para restauração (RTO)', null=True)),
                ('dr_test_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Backup / DRP',
                'verbose_name_plural': 'Registos de Backup / DRP',
                'ordering': ['-created_at'],
            },
        ),
    ]
