# Generated by Django 5.0.14 on 2026-09-02 16:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_databasebackuplog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberIncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('DDOS_ATTACK', 'Ataque de Negação de Serviço Distribuído (DDoS)'), ('DATA_LEAK_ATTEMPT', 'Tentativa de Fuga / Exfiltração de Dados'), ('BRUTE_FORCE_BURST', 'Ataque de Força Bruta / Credential Stuffing'), ('SYSTEM_OUTAGE', 'Indisponibilidade Não Programada do Sistema'), ('UNAUTHORIZED_ACCESS', 'Tentativa de Acesso Não Autorizado / Privilégios'), ('MALWARE_RANSOMWARE', 'Ameaça de Código Malicioso / Ransomware'), ('MAN_IN_THE_MIDDLE', 'Tentativa de Intercepção de Comunicações'), ('OTHER_INCIDENT', 'Outro Incidente Relevante de TI')], db_index=True, default='OTHER_INCIDENT', max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Baixa (Sem Impacto Financeiro/Operacional)'), ('MEDIUM', 'Média (Impacto Operacional Parcial)'), ('HIGH', 'Alta (Risco Iminente / Degradação de Serviços)'), ('CRITICAL', 'Crítica (Comprometimento de Dados ou Interrupção Severa)')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DETECTED', 'Detectado / Em Análise Inicial'), ('CONTAINED', 'Contido / Medidas de Mitigação Aplicadas'), ('REPORTED_TO_BNA', 'Notificado ao BNA (Prazo de 24h Cumprido)'), ('RESOLVED', 'Totalmente Resolvido e Encerrado')], db_index=True, default='DETECTED', max_length=30)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contained_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('bna_notified_at', models.DateTimeField(blank=True, null=True)),
                ('bna_protocol_number', models.CharField(blank=True, max_length=100)),
                ('bna_notification_notes', models.TextField(blank=True)),
                ('affected_systems', models.CharField(default='KwanzaConnect API / Infraestrutura', max_length=255)),
                ('impact_summary', models.TextField(help_text='Descrição sumária do impacto nas operações ou dados')),
                ('root_cause', models.TextField(blank=True, help_text='Causa raiz apurada')),
                ('remediation_actions', models.TextField(help_text='Medidas corretivas e preventivas adotadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente de Cibersegurança (BNA)',
                'verbose_name_plural': 'Incidentes de Cibersegurança (BNA)',
                'ordering': ['-created_at'],
            },
        ),
    ]
