# Generated by Django 5.0.14 on 2026-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-timestamp'], 'verbose_name': 'Registo de Auditoria', 'verbose_name_plural': 'Registos de Auditoria'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor_email',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(db_index=True, default='INFO', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(db_index=True, default='SUCCESS', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
