# Generated by Django 5.0.14 on 2026-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_interest', 'Novo interesse na tua oferta'), ('interest_accepted', 'O teu interesse foi aceite'), ('interest_rejected', 'O teu interesse foi rejeitado'), ('interest_cancelled', 'Um interessado cancelou'), ('offer_expired', 'A tua oferta expirou'), ('new_message', 'Nova mensagem'), ('deal_accepted', 'Acordo aceite na conversa'), ('deal_cancelled', 'Acordo cancelado'), ('rate_alert', 'Alerta de câmbio'), ('account_verified', 'Conta verificada'), ('account_rejected', 'Verificação rejeitada'), ('system', 'Notificação do sistema'), ('new_user_registration', 'Novo Utilizador Registado'), ('user_profile_updated', 'Perfil Atualizado'), ('kyc_submitted', 'Documento Submetido')], max_length=30),
        ),
    ]
